blank_issues_enabled: false
contact_links:
  - name: MyAnimeList
    url: https://myanimelist.net/
    about: MyAnimeList
  - name: MyAnimeList API Club
    url: https://myanimelist.net/clubs.php?cid=13727
    about: MyAnimeList API Club